# No live updates functionality anymore:
# https://github.blog/2021-04-29-goodbye-dependabot-preview-hello-dependabot/
# https://github.com/dependabot/dependabot-core/issues/3488
# https://github.com/Harmon758/Harmonbot/pull/2511

# No unlimited open pull requests anymore:
# https://github.com/Harmon758/Harmonbot/pull/2511
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#open-pull-requests-limit

# "The cron expression at property '#/updates/0/schedule/interval/cronjob' must have a minimum period of 24 hours between next job run."
# https://github.com/dependabot/dependabot-core/issues/6339#issuecomment-2772911033
# https://github.com/dependabot/dependabot-core/issues/6339#issuecomment-2810799331

version: 2

updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 0 * * *"
    labels:
      - "dependency update"
    open-pull-requests-limit: 1000

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 0 * * *"
    allow:
      - dependency-type: "all"
    groups:
      grpcio:
        patterns:
          - "grpcio*"
      psycopg:
        patterns:
          - "psycopg*"
      pyasn1:
        patterns:
          - "pyasn1*"
      pydantic:
        patterns:
          - "pydantic*"
    labels:
      - "dependency update"
    open-pull-requests-limit: 1000

  # https://github.com/dependabot/dependabot-core/issues/12094 (pylock.toml support)

  # https://github.com/dependabot/dependabot-core/issues/13199 (required-version)
  # https://github.com/dependabot/dependabot-core/issues/12696 (editable)
  # https://github.com/dependabot/dependabot-core/issues/12428 (indirect dependencies)
  # https://github.com/dependabot/dependabot-core/issues/11913 (indirect dependencies)
  # https://github.com/dependabot/dependabot-core/issues/12443 (extras)
  # https://github.com/dependabot/dependabot-core/issues/12124 (build-system)
  # https://github.com/dependabot/dependabot-core/issues/12273 (no constraints)
  # 
  # https://github.com/dependabot/dependabot-core/issues/10478
  # https://github.com/astral-sh/uv/issues/2512
  # 
  # - package-ecosystem: "uv"
  #   directory: "/"
  #   schedule:
  #     interval: "cron"
  #     cronjob: "0 0 * * *"
  #   allow:
  #     - dependency-type: "all"
  #   groups:
  #     grpcio:
  #       patterns:
  #         - "grpcio*"
  #     psycopg:
  #       patterns:
  #         - "psycopg*"
  #     pyasn1:
  #       patterns:
  #         - "pyasn1*"
  #     pydantic:
  #       patterns:
  #         - "pydantic*"
  #   labels:
  #     - "dependency update"
  #   open-pull-requests-limit: 1000
