version: 1.0.0-{build}

init:
  - cmd: SET PATH=%PYTHON%;%PYTHON%\Scripts;C:\Program Files\PostgreSQL\12\bin\;%PATH%

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: C:\Python38
      PYTHON_VERSION: 3.8.1
      PYTHON_ARCH: 32
      # https://www.appveyor.com/docs/services-databases/#postgresql
      PGUSER: postgres
      PGPASSWORD: Password12!
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: C:\Python38-x64
      PYTHON_VERSION: 3.8.1
      PYTHON_ARCH: 64
      # https://www.appveyor.com/docs/services-databases/#postgresql
      PGUSER: postgres
      PGPASSWORD: Password12!
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
    - APPVEYOR_BUILD_WORKER_IMAGE: macos

stack: Python 3.8.1

cache:
  - '%LOCALAPPDATA%\pip\Cache'

# services:
#   - postgresql12
# https://github.com/appveyor/ci/issues/3299

build_script:
  - cmd: net start postgresql-x64-12
  - cmd: createdb harmonbot
  - cmd: echo CREATE USER harmonbot SUPERUSER PASSWORD :'pgpassword' | psql --variable=pgpassword="%PGPASSWORD%"
  - sh: sudo --user=postgres createdb harmonbot
  - sh: sudo --user=postgres psql --variable=pgpassword="$PGPASSWORD" <<< "CREATE USER harmonbot SUPERUSER PASSWORD :'pgpassword'"

install:
  - pip install --upgrade --requirement requirements.txt

test_script:
  - cd Discord && python Harmonbot.py
  - cd ../Telegram && python Telegram_Harmonbot.py
