version: 1.2.2-{build}

environment:
  # https://www.appveyor.com/docs/services-databases/#postgresql
  PGUSER: postgres
  PGPASSWORD: Password12!
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PLATFORM: Discord
      PYTHON: C:\Python38
      PYTHON_VERSION: 3.8.3
      PYTHON_ARCH: 32
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PLATFORM: Discord
      PYTHON: C:\Python38-x64
      PYTHON_VERSION: 3.8.3
      PYTHON_ARCH: 64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PLATFORM: Telegram
      PYTHON: C:\Python38
      PYTHON_VERSION: 3.8.3
      PYTHON_ARCH: 32
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PLATFORM: Telegram
      PYTHON: C:\Python38-x64
      PYTHON_VERSION: 3.8.3
      PYTHON_ARCH: 64
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      PLATFORM: Discord
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      PLATFORM: Telegram
    - APPVEYOR_BUILD_WORKER_IMAGE: macos
      PLATFORM: Discord
    - APPVEYOR_BUILD_WORKER_IMAGE: macos
      PLATFORM: Telegram

matrix:
  allow_failures:
    - APPVEYOR_BUILD_WORKER_IMAGE: macos
    # PostgreSQL not available for macOS images yet
    # https://www.appveyor.com/docs/macos-images-software/

stack: Python 3.8.2, PostgreSQL 12.1
# Python 3.8.3 not installed for Ubuntu images yet
# https://www.appveyor.com/docs/linux-images-software/

# services:
#   - postgresql12
# https://github.com/appveyor/ci/issues/3299

init:
  - cmd: SET PATH=%PYTHON%;%PYTHON%\Scripts;C:\Program Files\PostgreSQL\12\bin\;%PATH%

cache:
  - '%LOCALAPPDATA%\pip\Cache'

install:
  - python -m pip install --upgrade pip
  - pip install --upgrade --requirement requirements.txt

for:
  -
    matrix:
      only:
        - PLATFORM: Discord
    build_script:
      - cmd: net start postgresql-x64-12
      # https://github.com/appveyor/ci/issues/3299
      - cmd: createdb harmonbot
      - cmd: echo CREATE USER harmonbot SUPERUSER PASSWORD :'pgpassword' | psql --variable=pgpassword="%PGPASSWORD%"
      - sh: sudo --user=postgres createdb harmonbot
      - sh: sudo --user=postgres psql --variable=pgpassword="$PGPASSWORD" <<< "CREATE USER harmonbot SUPERUSER PASSWORD :'pgpassword'"
    test_script:
      - cd Discord
      - python Harmonbot.py
  -
    matrix:
      only:
        - PLATFORM: Telegram
    build: off
    test_script:
      - cd Telegram
      - python Telegram_Harmonbot.py
