version: 1.0.0-{build}

for:
-
  matrix:
    only:
      - image: Visual Studio 2019
  init:
    - SET PATH=%PYTHON%;%PYTHON%\Scripts;C:\Program Files\PostgreSQL\12\bin\;%PATH%
  build_script:
    - net start postgresql-x64-12
    - createdb harmonbot
    - echo CREATE USER harmonbot SUPERUSER PASSWORD :'pgpassword' | psql --variable=pgpassword="%PGPASSWORD%"
-
  matrix:
    except:
      - image: Visual Studio 2019
  build_script:
    - sudo --user=postgres createdb harmonbot
    - sudo --user=postgres psql --variable=pgpassword="$PGPASSWORD" <<< "CREATE USER harmonbot SUPERUSER PASSWORD :'pgpassword'"

image:
  - Visual Studio 2019
  - Ubuntu1804
  - macos

environment:
  # https://www.appveyor.com/docs/services-databases/#postgresql
  PGUSER: postgres
  PGPASSWORD: Password12!
  matrix:
    - PYTHON: C:\Python38
      PYTHON_VERSION: 3.8.1
      PYTHON_ARCH: 32
    - PYTHON: C:\Python38-x64
      PYTHON_VERSION: 3.8.1
      PYTHON_ARCH: 64

stack: PostgreSQL 12.1, Python 3.8.1

cache:
  - '%LOCALAPPDATA%\pip\Cache'

# services:
#   - postgresql12
# https://github.com/appveyor/ci/issues/3299

install:
  - pip install --upgrade --requirement requirements.txt

test_script:
  - cd Discord && python Harmonbot.py
  - cd ../Telegram && python Telegram_Harmonbot.py
