version: 1.0.0-{build}

image:
  - Visual Studio 2019
  - Ubuntu1804
  - macos

environment:
  matrix:
    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8.1"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.1"
      PYTHON_ARCH: "64"

cache:
  - '%LOCALAPPDATA%\pip\Cache'

services:
  - postgresql121

build: off

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;C:\\Program Files\\PostgreSQL\\12\\bin\\;%PATH%"
  - pip install --upgrade --requirement requirements.txt
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - createdb harmonbot
  - createuser harmonbot --no-password

test_script:
  - cd Discord && python Harmonbot.py
  - cd ../Telegram && python Telegram_Harmonbot.py
