language: python
python:
  - "3.5"
cache: pip
before_install:
  - gimme 1.6
  - export GOROOT="/home/travis/.gimme/versions/go1.6.linux.amd64"
  - export GOPATH="/home/travis/.gimme/versions/go1.6.linux.amd64/bin:$TRAVIS_BUILD_DIR"
  - /home/travis/.gimme/versions/go1.6.linux.amd64/bin/go get github.com/bwmarrin/discordgo
  - /home/travis/.gimme/versions/go1.6.linux.amd64/bin/go get github.com/bwmarrin/dgvoice
script:
  - python Harmonbot.py
  - /home/travis/.gimme/versions/go1.6.linux.amd64/bin/go run Harmonbot_Listener.go

