matrix:
  include:
    - name: Discord
      language: python
      python: 3.7.3
      dist: xenial
      # Required for Python 3.7
      # https://docs.travis-ci.com/user/languages/python/#python-37-and-higher
      # https://github.com/travis-ci/travis-ci/issues/9815
      services:
        - postgresql
      addons:
        postgresql: "10"
      cache:
        pip: true
      before_script:
        - psql -c "CREATE DATABASE harmonbot"
        - psql -c "CREATE USER harmonbot SUPERUSER"
        - cd Discord
      script:
        - python Harmonbot.py
    - name: Telegram
      language: python
      python: 3.7.3
      dist: xenial
      # Required for Python 3.7
      # https://docs.travis-ci.com/user/languages/python/#python-37-and-higher
      # https://github.com/travis-ci/travis-ci/issues/9815
      cache:
        pip: true
      before_script:
        - cd Telegram
      script:
        - python Telegram_Harmonbot.py
    - name: Discord Listener
      language: go
      go: "1.12"
      install:
        - go get github.com/bwmarrin/discordgo
        - go get github.com/bwmarrin/dgvoice
        - go get github.com/joho/godotenv
      before_script:
        - cd Discord
      script:
        - go run Harmonbot_Listener.go
