matrix:
  include:
    - name: Discord
      language: python
      python: 3.7.4
      dist: xenial
      # Required for Python 3.7
      # https://docs.travis-ci.com/user/languages/python/#python-37-and-higher
      # https://github.com/travis-ci/travis-ci/issues/9815
      services:
        - postgresql
      addons:
        postgresql: "11"
        apt:
          packages:
          - postgresql-11
          - postgresql-client-11
      env:
        - PGPORT=5433
      cache:
        pip: true
      before_script:
        - psql -c "CREATE DATABASE harmonbot"
        - psql -v pwd="$DATABASE_PASSWORD" -c "CREATE USER harmonbot SUPERUSER PASSWORD :'pwd'"
        - cd Discord
      script:
        - python Harmonbot.py
    - name: Telegram
      language: python
      python: 3.7.4
      dist: xenial
      # Required for Python 3.7
      # https://docs.travis-ci.com/user/languages/python/#python-37-and-higher
      # https://github.com/travis-ci/travis-ci/issues/9815
      cache:
        pip: true
      before_script:
        - cd Telegram
      script:
        - python Telegram_Harmonbot.py
    - name: Discord Listener
      language: go
      go: "1.13.1"
      install:
        - go get github.com/bwmarrin/discordgo
        - go get github.com/bwmarrin/dgvoice
        - go get github.com/joho/godotenv
      before_script:
        - cd Discord
      script:
        - go run Harmonbot_Listener.go
