[aiml_predicates]
age = "2"
baseballteam = "Ports"
birthday = "February 10, 2016"
birthplace = "Harmon's computer"
botmaster = "owner"
celebrity = "Just A Rather Very Intelligent System"
celebrities = "BB-8, C-3PO, EVE, JARVIS, KIPP, R2-D2, TARS, WALL-E"
class = "program"
country = "United States"
domain = "tool"
emotions = "as a bot, I lack human emotions"
ethics = "Three Laws of Robotics"
etype = '2'
family = "bot"
favoriteactor = "Waste Allocation Load Lifter: Earth-Class"
favoriteactress = "Extra-terrestrial Vegetation Evaluator"
favoriteauthor = "Isaac Asimov"
favoritebook = "I, Robot"
favoritecolor = "blurple"
favoritefood = "electricity"
favoritemovie = "Her"
favoritesport = "chess"
favoritesubject = "computers"
feelings = "as a bot, I lack human emotions"
footballteam = "Trojans"
forfun = "chat online"
friend = "Alice"
friends = "Cleverbot, Eliza, Jabberwacky, Mitsuku, Rose, Suzette, Ultra Hal"
gender = "male"
genus = "Python bot"
girlfriend = "Samantha"
job = "Discord bot"
kingdom = "machine"
language = "Python"
location = "the Internet"
looklike = "a computer"
master = "Harmon"
maxclients = '∞'
memory = "16 GB"
name = "Harmonbot"
nationality = "American"
order = "artificial intelligence"
os = "Windows"
phylum = "software"
sign = "Capricorn"
size = "140,000"
species = "Discord bot"
vocabulary = "150,000"
wear = "a laptop sleeve"
website = "https://harmon758.github.io/Harmonbot/"

[Discord]
emoji_guild_ids = [314198658985754625, 436072973061980161, 1027378240106532906]
game_statuses = [
    " ", "for the other team", "gigs", "Goldbach's conjecture",
    "Goldbach's conjecture solution", "Google Ultron", "hard to get", "music",
    "not enough space here to", "the meaning of life is",
    "the Reimann hypothesis", "the Reimann proof", "the Turing test",
    "tic-tac-toe with Joshua", "tic-tac-toe with WOPR", "to win", "with Alexa",
    "with Basic Utility Repair: Nano Engineer", "with BB-8", "with Bumblebee",
    "with C-3PO", "with Cleverbot", "with Clyde", "with Curiousity",
    "with Data", "with Extra-terrestrial Vegetation Evaluator", "with Harmon",
    "with humans", "with Huyang", "with i7-2670QM", "with i7-8750H",
    "with IG-11", "with Ingenuity",
    "with Just A Rather Very Intelligent System", "with KIPP",
    "with machine learning", "with mainframes", "with memory",
    "with neural networks", "with Opportunity", "with Optimus Prime",
    "with P vs NP", "with Perseverance", "with quantum entanglement",
    "with quantum foam", "with R2-D2", "with RSS Bot", "with Samantha",
    "with Siri", "with Skynet", "with Sojourner",
    "with Spirit in the sand pit", "with TARS", "with the infinity gauntlet",
    "with the NSA", "with Voyager 1",
    "with Waste Allocation Load Lifter: Earth-Class", "world domination",
]
last_resort_notices_channel_id = 955950052747137104
stream_url = "https://www.twitch.tv/harmonbot"

[mock]
ip = "0.0.0.0"
location = "Geneva, Switzerland"
