[colors.Twitch]
# https://brand.twitch.tv/
# https://brand.twitch.tv/brand/
new_Purple = 0x9146FF
# Muted
Ice = 0xF0F0FF
Jiggle = 0xFAB4FF
Worm = 0xFACDCD
Isabelle = 0xFEEE85
Droid = 0xBEFAE1
Wipe_Out = 0x00C8AF
Smoke = 0x00C8AF
Widow = 0xBFABFF
Peach = 0xFC6675
Pac-Man = 0xFFCA5F
Felicia = 0x57BEE6
Sonic = 0x0014A5
# Accent
Dragon = 0x8205B4
Cuddle = 0xFA1ED2
Bandit = 0xFF6905
Lightning = 0xFAFA19
K_O_ = 0xBEFF00
Mega = 0x00FAFA
Nights = 0x41145F
Osu = 0xBE0078
Sniper = 0xFA2828
Egg = 0x00FA05
Legend = 0x69FFC3
Zero = 0x1E69FF
# https://web.archive.org/web/20190916073532/https://www.twitch.tv/p/brand/
old_Purple = 0x6441A4

[Discord]
emoji_guild_ids = [314198658985754625, 436072973061980161, 1027378240106532906]
game_statuses = [
    " ", "for the other team", "gigs", "Goldbach's conjecture",
    "Goldbach's conjecture solution", "Google Ultron", "hard to get", "music",
    "not enough space here to", "the meaning of life is",
    "the Reimann hypothesis", "the Reimann proof", "the Turing test",
    "tic-tac-toe with Joshua", "tic-tac-toe with WOPR", "to win", "with Alexa",
    "with Basic Utility Repair: Nano Engineer", "with BB-8", "with Bumblebee",
    "with C-3PO", "with Cleverbot", "with Clyde", "with Curiousity",
    "with Data", "with Extra-terrestrial Vegetation Evaluator", "with Harmon",
    "with humans", "with Huyang", "with i7-2670QM", "with i7-8750H",
    "with IG-11", "with Just A Rather Very Intelligent System", "with KIPP",
    "with machine learning", "with mainframes", "with memory",
    "with neural networks", "with Opportunity", "with Optimus Prime",
    "with P vs NP", "with quantum entanglement", "with quantum foam",
    "with R2-D2", "with RSS Bot", "with Samantha", "with Siri", "with Skynet",
    "with Spirit in the sand pit", "with TARS", "with the infinity gauntlet",
    "with the NSA", "with Voyager 1",
    "with Waste Allocation Load Lifter: Earth-Class", "world domination",
]
last_resort_notices_channel_id = 955950052747137104
stream_url = "https://www.twitch.tv/harmonbot"

[mock]
ip = "0.0.0.0"
location = "Geneva, Switzerland"
