[project]
name = "Harmonbot"
dynamic = ["version"]
requires-python = "~=3.10.11"

[build-system]
requires = ["setuptools==68.2.2"]
build-backend = "setuptools.build_meta"

[tool.mypy]
packages = ["units"]
python_version = "3.10"

[tool.ruff]
ignore = [
    "UP015",  # redundant-open-modes
]
include = ["tests/*.py", "units/*.py"]
select = [
    "E4", "E7", "E9", "F",  # default
    "PYI041",  # redundant-numeric-union
    "UP",  # pyupgrade
]
target-version = "py310"

[tool.setuptools]
packages = ["units"]
