[project]
name = "Harmonbot"
dynamic = ["version"]
requires-python = "==3.11.*"
dependencies = [
    "discord-py[speed,voice]",
    "discord-ext-menus",
    "discord-ext-voice-recv[extras_speech]",
    "twitchio",
    "irc",
    "python-telegram-bot",

    "aiocache",
    "aiohttp[speedups]",
    "async-lru",
    "asyncpg",
    "beautifulsoup4[lxml]",
    "chess",
    "clarifai",
    "cryptography",
    "dice",
    "emoji",
    "en_core_web_md",
    "feedparser",
    "gidgethub",
    "GitPython",
    "google-api-core[grpc]",
    "google-cloud-translate",
    "imageio",
    "imgurpython",
    "inflect",
    "isodate",
    "markdownify",
    "matplotlib",
    "more-itertools",
    "numexpr",
    "numpy",
    "packaging",
    "pandas",
    "parsedatetime",
    "pillow",
    "psutil",
    "py-cpuinfo",
    "pycountry",
    "pycryptodomex",
    "pydantic",
    "pydealer",
    # pygost==5.6  # No longer on PyPI
    "pyowm",
    "pyparsing",
    "pyspellchecker",
    "python-aiml",
    "python-dateutil",
    "python-dotenv",
    "pytz",
    "requests[socks]",
    "scipy",
    "seaborn",
    "sentry-sdk",
    "spacy",
    "spacy-entity-linker",
    "SpeechRecognition",
    "sphobjinv",
    "sympy",
    "tabulate",
    "treys",
    "tweepy[async]",
    "typing-extensions",
    "unicodedata2",
    "wand",
    "wolframalpha",
    "wordcloud",
    "wordnik-py3",
    "youtube-dl",
    "yt-dlp[default]",
]

[project.optional-dependencies]
scripts = ["psycopg[binary]", "rich", "SQLAlchemy"]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[dependency-groups]
build = ["setuptools", "setuptools-scm"]
dev = [
    "Harmonbot[scripts]",
    "uv",
    {include-group = "build"},
    {include-group = "lint"},
    {include-group = "test"},
    {include-group = "type-check"},
]
lint = ["ruff"]
test = ["hypothesis", "pytest", "vcrpy"]
type-check = ["mypy[faster-cache]", "pycroscope", "pyrefly", "pytype", "ty"]

[tool.bandit.assert_used]
skips = ["./tests/*.py"]  # https://github.com/PyCQA/bandit/issues/1106

[tool.mypy]
packages = ["units"]
python_version = "3.11"

[tool.pyrefly]
project-includes = [
    "units",
]
python-version = "3.11"

[tool.pytype]
inputs = ["units"]

[tool.ruff]
include = ["tests/*.py", "units/*.py"]

[tool.ruff.lint]
ignore = [
    "E501",  # line-too-long
    "TD002",  # missing-todo-author
    "TD003",  # missing-todo-link
    "UP015",  # redundant-open-modes
]
select = [
    "E",  # pycodestyle error
    "EXE",  # flake8-executable
    "F",  # Pyflakes
    "FA",  # flake8-future-annotations
    "FLY",  # flynt
    "FURB",  # refurb
    "PGH",  # pygrep-hooks
    "PIE",  # flake8-pie
    "PLE",  # Pylint Error
    "PYI",  # flake8-pyi
    "RSE",  # flake8-raise
    "S",  # flake8-bandit
    "SLOT",  # flake8-slots
    "TC",  # flake8-type-checking
    "TD",  # flake8-todos
    "UP",  # pyupgrade
    "YTT",  # flake8-2020
]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["S101"]  # assert

[tool.setuptools]
packages = ["units"]

[tool.setuptools_scm]
fallback_version = "0.0.0"

[tool.ty.src]
include = ["units"]

[tool.uv]
cache-dir = "./.uv_cache"
environments = [
    "implementation_name == 'cpython' and platform_python_implementation == 'CPython'"
    # https://github.com/astral-sh/uv/issues/11151
    # https://github.com/astral-sh/uv/issues/14886
]
override-dependencies = [
    # https://github.com/Clarifai/clarifai-python/issues/769
    "psutil >= 7.1.1",
    "pydantic >= 2.12.2",
    "pydantic-core >= 2.41.4",
    "ruff >= 0.14.1",
    "uv >= 0.8.22",
]

[tool.uv.sources]
discord-py = { git = "https://github.com/Rapptz/discord.py.git", rev = "2175bd5" }
discord-ext-menus = { git = "https://github.com/Rapptz/discord-ext-menus.git", rev = "8686b5d" }
# https://github.com/explosion/spacy-models/releases/tag/en_core_web_md-3.8.0
en_core_web_md = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.8.0/en_core_web_md-3.8.0-py3-none-any.whl" }
# https://github.com/ytdl-org/youtube-dl/issues/31585
# https://github.com/ytdl-org/ytdl-nightly/releases/tag/2023.12.07
youtube-dl = { url = "https://github.com/ytdl-org/ytdl-nightly/releases/download/2023.12.07/youtube-dl-2023.12.07.tar.gz" }
