[project]
name = "Harmonbot"
dynamic = ["version"]
requires-python = "==3.10"
# ==3.10.11
# https://github.com/actions/setup-python/issues/711

[tool.mypy]
packages = ["units"]
python_version = "3.10"

[tool.ruff]
include = ["tests/*.py", "units/*.py"]
select = [
    "E4", "E7", "E9", "F",  # default
    "PYI041"  # redundant-numeric-union
]
target-version = "py310"
