name: Platforms

on: push

jobs:
  discord:
    name: Discord

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
        # Container action (for PostgreSQL) is only supported on Linux
        postgresql-version: ['12.1']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up PostgreSQL ${{ matrix.postgresql-version }}
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: ${{ matrix.postgresql-version }}
        postgresql db: harmonbot
        postgresql user: harmonbot
        postgresql password: ""
    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version-file: pyproject.toml
        architecture: x64
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test Discord Harmonbot
      env:
        DISCORD_BETA_BOT_TOKEN: ${{ secrets.DISCORD_BETA_BOT_TOKEN }}
      run: |
        cd Discord
        python Harmonbot.py

  telegram:
    name: Telegram

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version-file: pyproject.toml
        architecture: x64
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test Telegram Harmonbot
      env:
        TELEGRAM_BOT_API_TOKEN: ${{ secrets.TELEGRAM_BOT_API_TOKEN }}
      run: |
        cd Telegram
        python Telegram_Harmonbot.py

  discord_listener:
    name: Discord Listener

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        go-version: ['1.20.9']
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5.0.0
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
    - name: Get dependencies
      run: |
        go get github.com/bwmarrin/discordgo
        go get github.com/bwmarrin/dgvoice
        go get github.com/joho/godotenv
    - name: Test Discord Listener
      env:
        DISCORD_LISTENER_BOT_TOKEN: ${{ secrets.DISCORD_LISTENER_BOT_TOKEN }}
      run: |
        cd Discord
        go run Harmonbot_Listener.go
