name: Platforms

on: push

jobs:
  discord:
    name: Discord

    strategy:
      max-parallel: 1
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: ['3.7']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test Discord Harmonbot
      run: |
        cd Discord
        python Harmonbot.py

  telegram:
    name: Telegram

    strategy:
      max-parallel: 1
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: ['3.7']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test Telegram Harmonbot
      run: |
        cd Telegram
        python Telegram_Harmonbot.py

  discord_listener:
    name: Discord Listener

    strategy:
      max-parallel: 1
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        go-version: ['1.10']
    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Get dependencies
      run: |
        go get github.com/bwmarrin/discordgo
        go get github.com/bwmarrin/dgvoice
        go get github.com/joho/godotenv
    - name: Test Discord Listener
      run: |
        cd Discord
        go run Harmonbot_Listener.go
