name: Platforms

on: push

jobs:
  discord:
    name: Discord

    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
        # Container action (for PostgreSQL) is only supported on Linux
        postgresql-version: ['12.0']
        python-version: ['3.7.5']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1.1.0
    - name: Set up PostgreSQL ${{ matrix.postgresql-version }}
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: ${{ matrix.postgresql-version }}
        postgresql db: harmonbot
        postgresql user: harmonbot
        postgresql password: ""
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1.1.1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Cache pip
      uses: actions/cache@v1.0.3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test Discord Harmonbot
      env:
        DISCORD_BETA_BOT_TOKEN: ${{ secrets.DISCORD_BETA_BOT_TOKEN }}
      run: |
        cd Discord
        python Harmonbot.py

  telegram:
    name: Telegram

    strategy:
      max-parallel: 1
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: ['3.7.5']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1.1.0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1.1.1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - uses: actions/cache@v1.0.3
      if: startsWith(runner.os, 'Linux')
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - uses: actions/cache@v1.0.3
      if: startsWith(runner.os, 'macOS')
      with:
        path: ~/Library/Caches/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - uses: actions/cache@v1.0.3
      if: startsWith(runner.os, 'Windows')
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test Telegram Harmonbot
      env:
        TELEGRAM_BOT_API_TOKEN: ${{ secrets.TELEGRAM_BOT_API_TOKEN }}
      run: |
        cd Telegram
        python Telegram_Harmonbot.py

  discord_listener:
    name: Discord Listener

    strategy:
      max-parallel: 1
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        go-version: ['1.13.4']
    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1.1.1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1.1.0
    - name: Get dependencies
      run: |
        go get github.com/bwmarrin/discordgo
        go get github.com/bwmarrin/dgvoice
        go get github.com/joho/godotenv
    - name: Test Discord Listener
      env:
        DISCORD_LISTENER_BOT_TOKEN: ${{ secrets.DISCORD_LISTENER_BOT_TOKEN }}
      run: |
        cd Discord
        go run Harmonbot_Listener.go
