name: Tests

on: push

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
    - name: Set up Python
      uses: actions/setup-python@v6.2.0
      with:
        python-version-file: pyproject.toml
        architecture: x64
        cache: pip
    - name: Set up uv
      uses: astral-sh/setup-uv@v6.8.0
    - name: Install dependencies
      run: uv pip install -r pylock.toml --system
    - name: Run pytest
      run: pytest

  mypy:
    name: Mypy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
    - name: Set up Python
      uses: actions/setup-python@v6.2.0
      with:
        python-version-file: pyproject.toml
        architecture: x64
        cache: pip
    - name: Set up uv
      uses: astral-sh/setup-uv@v6.8.0
    - name: Install dependencies
      run: uv pip install -r pylock.toml --system
    - name: Run mypy
      run: mypy

  pytype:
    name: Pytype
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
    - name: Set up Python
      uses: actions/setup-python@v6.2.0
      with:
        python-version-file: pyproject.toml
        architecture: x64
        cache: pip
    - name: Set up uv
      uses: astral-sh/setup-uv@v6.8.0
    - name: Install dependencies
      run: uv pip install -r pylock.toml --system
    - name: Run pytype
      run: pytype --config pytype.toml

  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
    - name: Set up Python
      uses: actions/setup-python@v6.2.0
      with:
        python-version-file: pyproject.toml
        architecture: x64
        cache: pip
    - name: Set up uv
      uses: astral-sh/setup-uv@v6.8.0
    - name: Install dependencies
      run: uv pip install -r pylock.toml --system
    - name: Run Ruff
      run: ruff check
