name: Tests

on: push

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.6
    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version-file: pyproject.toml
        architecture: x64
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Unit Test
      run: python -m unittest

  mypy:
    name: Mypy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.6
    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version-file: pyproject.toml
        architecture: x64
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run mypy
      run: mypy

  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.6
    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version-file: pyproject.toml
        architecture: x64
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Ruff
      run: ruff check
